### ISSUE TITLE
Create a web page

### ISSUE THREAD

**Issue by C-STYR** [C-STYR/GitHubTrainer#32]
1. Add a new directory to `/abehenderson`
2. Inside it, add an `html` file and a `css` file that defines a new web page
3. The page should have: 
 - [x] a header
 - [x] a picture
 - [x] an input field
 - [x] a submit button

**Comment by a-hend** [comment]
Let me know if this satisfies the requirements...I realize a Mailchimp input form isn't what you probably had in mind, but I've created input fields and submit buttons, and photos and headers in other projects for ZTM.  Just let me know.
